from django.urls import path
from post import views

urlpatterns = [
    path('posts',
         views.get_posts.as_view(),
         name='list_posts'),
    path('posts/create/',
         views.create_post.as_view(),
         name='create_post'),
    path('posts/<int:post_id>/update/',
         views.update_post.as_view(),
         name='update_post'),
    path('posts/<int:post_id>/delete/',
         views.delete_post.as_view(),
         name='delete_post'),
    path('posts/<int:post_id>/like/',
         views.like_post.as_view(),
         name='like_post'),
    path('posts/<int:post_id>/comment/',
         views.comment_on_post.as_view(),
         name='comment_on_post'),
    path('posts/liked/',
         views.liked_posts.as_view(),
         name='liked_posts'),
    path('posts/commented/',
         views.commented_posts.as_view(),
         name='commented_posts'),
    path('feed/',
         views.feed.as_view(),
         name='feed'),
]
